title: "PBUF Cosmology: Unified Fit Comparison"
subtitle: "Mock validation runs"
theme:
  primary: "#0b3d91"
  secondary: "#ff6f00"
  background: "#ffffff"
  text: "#222222"
disclaimer: "⚠️ Results derived from internal mock datasets. Not for scientific use."
footer:
  contact: "cosmo-team@example.com"
  version: "v0.1.0"
