"""Branding constants for Cosmos2 outputs."""

from __future__ import annotations

__all__ = [
    "COSMOS2_DISPLAY_NAME",
    "COSMOS2_VERSION",
    "COSMOS2_BRANDING",
    "COSMOS2_GENERATED_FOOTER",
]

COSMOS2_DISPLAY_NAME = "Cosmos2"
COSMOS2_VERSION = "2025.12.7-beta" # release is as follows: year.month.version

COSMOS2_BRANDING = f"{COSMOS2_DISPLAY_NAME} Version {COSMOS2_VERSION}"
COSMOS2_GENERATED_FOOTER = f"Generated by {COSMOS2_BRANDING}"
